name: Test and Analysis
on:
  push:
    branches: [ master, develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
    services:
      mysql:
        image: 'mysql:latest'
        env:
          MYSQL_DATABASE: 'cache'
          MYSQL_USER: 'username'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Environment Setup (Python ${{ matrix.python-version }})
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry check
          poetry install

      - name: Check Code Style
        run: poetry run flake8

      - name: Test Execution
        run: poetry run pytest